const CACHE='tx-master-os-v2.6.0';
const AI_CACHE='tx-ai-assets-v1';
const CORE=['./','./index.html','./styles.css','./app.js','./meta-chain.js','./collaboration.js','./ai-resilience.js','./ai-tiered-stack.js','./public-inference.js','./webllm-worker.js','./manifest.webmanifest','./icons/texas-master.svg','./icons/texas-master-192.png','./icons/texas-master-512.png','./offline.html','./models/model-pack-index.json','./data/texas-status.json','./data/collaboration-roles.json','./data/extra-modules.json','./data/advanced-guides-additions.json'];
const AI_HOSTS=new Set(['huggingface.co','raw.githubusercontent.com','cdn.jsdelivr.net','esm.run','unpkg.com']);
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('tx-master-os-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
function isAIAsset(req){try{const u=new URL(req.url);return AI_HOSTS.has(u.hostname)||u.pathname.endsWith('/vendor/webllm-0.2.85.mjs')}catch{return false}}
async function aiCacheFirst(req){const c=await caches.open(AI_CACHE),hit=await c.match(req);if(hit)return hit;const r=await fetch(req);if(r.ok||r.type==='opaque')c.put(req,r.clone()).catch(()=>{});return r}
async function retryFetch(url,retries=3){let last;for(let i=0;i<retries;i++){try{const r=await fetch(url,{mode:'cors',credentials:'omit',cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r}catch(e){last=e;if(i<retries-1)await new Promise(res=>setTimeout(res,600*(i+1)))}}throw last}
self.addEventListener('message',e=>{const m=e.data||{},port=e.ports?.[0];if(m.type==='AI_STAGE'&&port){e.waitUntil((async()=>{try{const urls=[...new Set(m.plan?.urls||[])],c=await caches.open(AI_CACHE);let done=0,cached=0,downloaded=0;for(const url of urls){const existing=await c.match(url);if(existing){cached++;done++;port.postMessage({type:'AI_STAGE_PROGRESS',url,done,total:urls.length,status:'cached'});continue}const r=await retryFetch(url,Math.max(1,Math.min(5,Number(m.retries)||3)));await c.put(new Request(url,{mode:'cors'}),r.clone());downloaded++;done++;port.postMessage({type:'AI_STAGE_PROGRESS',url,done,total:urls.length,status:'downloaded'})}port.postMessage({type:'AI_STAGE_DONE',done,total:urls.length,cached,downloaded})}catch(err){port.postMessage({type:'AI_STAGE_ERROR',error:String(err?.message||err)})}})())}});
self.addEventListener('fetch',e=>{const req=e.request;if(req.method!=='GET')return;const u=new URL(req.url);if(isAIAsset(req)){e.respondWith(aiCacheFirst(req));return}if(u.origin!==location.origin)return;if(req.mode==='navigate'){e.respondWith(fetch(req).then(r=>{const cp=r.clone();caches.open(CACHE).then(c=>c.put('./index.html',cp));return r}).catch(()=>caches.match('./index.html').then(r=>r||caches.match('./offline.html'))));return}if(u.pathname.includes('/data/')){e.respondWith(caches.match(req).then(cached=>{const network=fetch(req).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put(req,r.clone()));return r}).catch(()=>cached);return cached||network}));return}e.respondWith(caches.match(req).then(cached=>cached||fetch(req).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put(req,r.clone()));return r}))) });
